- name: Deploy to VM using SSH
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ 192.168.183.128 }}      # Your VM's IP or hostname
    username: ${{ chima }}  # Your SSH user (e.g., ubuntu)
    key: ${{ -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEArJ707brQoiBkNGFgNaNe6ZeApN0rGso0cS6iXjs15lRjQeb6Qw8g
zFetqUmndCxpjgtQibcDOm8ERuB5C/oUpMUnxhy10w9LcQsr3SFn0juVV2OtWWJyoRYnZm
6PAR95Yf0g279+40EV7joJsacHfH2shACSrd1UVesAXHFZvQIv68rzDL/WBQ3VEilpcG5/
itmCvIjCCqEVByPX4uJDzh9RKq0svJSGnOAXeUhsBbQPm6EuucfwjCI55Oj6ySEZp2uYJA
FkvS3jl8bxQajNV/yA59PcFx35BeoNZ1rpwOb7vHXoqlGIs1ii0F6+qAwSiO3215sSEmcW
tlNa3sl8rOx84TFKBvBrqXbQCAnbZnAVAPWI4fb5j+GCqPq9P9sqBobMqFM08KhWxA84j5
yIH926T36/3mIug56MTbOfB6freDvC1fK3EgoDhMh2lzCmIyJh6BzYHVtVhfCfeDSeuHF8
ASCH6WoF7Fd6QMDuLhPATlt3WODltpug7RdwrvfWsh3TsKAS1Odzo5sPsZLb0C49hiIWGe
OBQQexWkGU0YLGWBsWFqscgN6iKd5TmW8Mii3bXgiVWd37Yo3sUsPOUWE9iAM0Hxc9WzWg
I0/7FNI3EuukoPNuhWBovZC6EoUZTvLvQ4IDyufLIE8JGK03tK5D8wBcwsr1xcdSLAZPf+
sAAAdINVPc7jVT3O4AAAAHc3NoLXJzYQAAAgEArJ707brQoiBkNGFgNaNe6ZeApN0rGso0
cS6iXjs15lRjQeb6Qw8gzFetqUmndCxpjgtQibcDOm8ERuB5C/oUpMUnxhy10w9LcQsr3S
Fn0juVV2OtWWJyoRYnZm6PAR95Yf0g279+40EV7joJsacHfH2shACSrd1UVesAXHFZvQIv
68rzDL/WBQ3VEilpcG5/itmCvIjCCqEVByPX4uJDzh9RKq0svJSGnOAXeUhsBbQPm6Euuc
fwjCI55Oj6ySEZp2uYJAFkvS3jl8bxQajNV/yA59PcFx35BeoNZ1rpwOb7vHXoqlGIs1ii
0F6+qAwSiO3215sSEmcWtlNa3sl8rOx84TFKBvBrqXbQCAnbZnAVAPWI4fb5j+GCqPq9P9
sqBobMqFM08KhWxA84j5yIH926T36/3mIug56MTbOfB6freDvC1fK3EgoDhMh2lzCmIyJh
6BzYHVtVhfCfeDSeuHF8ASCH6WoF7Fd6QMDuLhPATlt3WODltpug7RdwrvfWsh3TsKAS1O
dzo5sPsZLb0C49hiIWGeOBQQexWkGU0YLGWBsWFqscgN6iKd5TmW8Mii3bXgiVWd37Yo3s
UsPOUWE9iAM0Hxc9WzWgI0/7FNI3EuukoPNuhWBovZC6EoUZTvLvQ4IDyufLIE8JGK03tK
5D8wBcwsr1xcdSLAZPf+sAAAADAQABAAACAACY85USZUrNB5EXgzCRq7BC9NAymcXCdxMA
i9GoAnmVHNuAs/4LwoZ33o3W8kGYg8GuRVhCA2dY31rAHSXO9vJTt7MGV2oZw/OUtnv8nn
I1AEEoralrtKTdFu7SVCQMsAFdpxb2SeH50DHJDqPdmveHLH6FIqd/vB0orpF4rPcBV8Qe
VDVc6/M23IrEYkKK3LMmKenYI//LFe+2jovmUkDCN/2IqD57hHRs4XfrKcCNTSkx53T/fa
l71tfK0foPPMT+aNeQZQEInyCKhjw+xtMr+GWVBKPUgo+kLeldKwZJZmFScSc3GAeIN4Fh
dTx5/43CG8LG8nWQ2McccRSTUvSkI4xY8mu8wpsHe9LVdKi+ImZvXsojufP0xzgvLQYpVt
Pm/uib39ez5oojYrIUAOUcIX6txGuOrr+wl1ZEkj/MB6emppJFQz85LyIfsUQOYvzwuEcP
0IgyNSY9Uo34EcqPBwujPLWT7PwKfWxufsqBTGvPkW8P57Ix2Ogf84T2Z/dRH5p/18Yp3U
9/G52LohtwB9ZkDAlGCRmWSM5M0p9rYzi7xpqpZejv4qTCZj7J5lLiOHhDFpycIwMu5LQV
7fBfpN6KGr/hHGE+Nz/J5PRNfakB/OpZ4yiL0fevvaytej36woJMom7leieUHKxR8XpydZ
DpnPnUsUZUfbi0dGApAAABAFTKUXI94EQ3Kx8oGCzihI3rAeyti8LfIqxrbU2wYQ8kqsry
nX8aMhyFCToc98XuYCTes9JsESwd0yP8CN27KarS9bOZpYFvdrgAkcDk9noH2olca3+g1n
HAQ1wpsv5SItX+dNZ8pt93MvAFssOA4gaGNBMjflWwfeUX7OrezyEnF0+yPRgnAPn03Pjv
8fqwBoY0e3kF45RWmyUo9FdGm4C6nosfZpZa41CWGwjveFxqcERjEb5MWMDRyOn2hlPIt9
ZiL6nD7UwTHLNLNpfyoCGz97HkTJcoVhxbLc1/Wk4FKGKHl+HAotfcmj5oQX/M6QW+C/rQ
ibLAFU48tk/DgTcAAAEBAOXfs7vXFSmlz6q/kMcfZ+r8SnROn8ZaWE3iXN3twv1kPlW5NG
F+Hlq00yOpWncd0P2PeCVlNGAqDRfrrUkHuEzC6disYUNRBaodLyvccqONmSkp2pwA2ehX
v1GdH9YjnqCroya9vcFuEI4tDWjItDLatcpBgysXaaoSCfdGtCxL21OTmBWuj9KKgP48k6
jaUIlAx31oyshDYR6FgbFAFC8kDsFZvd1SiLWZU3BEcsHk1hqfy50qZn35wZdCVUGe6lyu
eSHB2fyd/hXOB+MjzpZaY5J3cLKUzy8LepyK7zdFxPVW9FYBHzbX4NNeLpSMkfqj7JKGT3
hiWeymT0wD4wMAAAEBAMA9c5/YHudNhK0xxuMAPNMvBKLU3PnIBCdFrUnoH7l7ZjRMhC1l
Sdi9K+EGgIlTO3j41YxnpxIJTzTGZ7bwbbNuItOx6a5AEYfwJOc2jAU9acMtY7xcnLaBIJ
AxmtC8+muADSa6xG3WJ/6SsmbBOFHWnOfVwiRNt7vWBPSNBBiN+RxZuf0Co+oNyGsKbrQJ
seYic+k6BRpxpqv49uPu5NC/Tg5N0P7NKjyxld04Ic9zL8r7EwMqlfyNlolRy+OXdEdvcF
gvg4WLlyNnQ1PtDy7s3OODtOVssMMfvwz7UKbjAu9QA2UeGROkv6cFp2Dv6ieqg+AjcgEC
v9JWPrcx5vkAAAANZ2l0aHViLWFjdGlvbgECAwQFBg==
-----END OPENSSH PRIVATE KEY----- }}
    script: |
      echo "Pulling latest image..."
      docker pull swimpyblaq92/chima:${{ env.IMAGE_TAG }}
      
      echo "Stopping existing container..."
      docker stop my_app_container || true
      docker rm my_app_container || true
      
      echo "Starting new container..."
      docker run -d --name my_app_container -p 80:80 swimpyblaq92/chima:${{ env.IMAGE_TAG }}
