name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Image Tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag swimpyblaq92/chima:${{ env.IMAGE_TAG }}

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image to Docker Hub
        run: docker push swimpyblaq92/chima:${{ env.IMAGE_TAG }}

      - name: Save Image Tag for Deployment
        run: echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" >> $GITHUB_ENV
        id: set_image_tag

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH Key
        run: echo "${{ secrets.VM_SSH_KEY }}" | base64 --decode > ~/.ssh/github-action-key && chmod 600 ~/.ssh/github-action-key

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            echo "Testing SSH Connection..."
            whoami

      - name: Deploy to VM using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e  # Stop execution on any error
            
            echo "Ensuring Docker is installed and running..."
            sudo systemctl start docker || true

            echo "Pulling latest image..."
            docker pull swimpyblaq92/chima:${{ env.IMAGE_TAG }}

            echo "Stopping and removing existing container..."
            docker stop my_app_container || true
            docker rm my_app_container || true

            echo "Cleaning up old Docker images..."
            docker system prune -f || true

            echo "Starting new container..."
            docker run -d --name my_app_container -p 80:80 swimpyblaq92/chima:${{ env.IMAGE_TAG }}
