- name: Set up SSH
  uses: webfactory/ssh-agent@v0.5.4
  with:
    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

- name: Deploy to VM
  run: |
    ssh -o StrictHostKeyChecking=no user@your-vm-ip << 'EOF'
      echo "Pulling latest image..."
      docker pull swimpyblaq92/chima:${{ env.IMAGE_TAG }}
      
      echo "Stopping existing container..."
      docker stop my_app_container || true
      docker rm my_app_container || true
      
      echo "Starting new container..."
      docker run -d --name my_app_container -p 80:80 swimpyblaq92/chima:${{ env.IMAGE_TAG }}
    EOF
